server:
  port: 8081

spring:
  application:
    name: inventory-service
  #  active mq configuration
  artemis:
    user: artemis
    password: simetraehcapa
  # port configuration to zipkin
  zipkin:
    enabled: false
  # spring security basic authentication configuration
  security:
    user:
      name: zeeroiq
      password: password
  # Spring Data hangs when not set under Spring Boot 2.3.0
  data:
    jpa:
      repositories:
        bootstrap-mode: default

logging:
  level:
    com:
      shri: debug