server:
  port: 8081

spring:
  application:
    name: inventory-service
  #  active mq configuration
  artemis:
    user: artemis
    password: simetraehcapa

logging:
  level:
    com:
      shri: debug