server:
  port: 8081

spring:
  application:
    name: inventory-service
  #  active mq configuration
  artemis:
    user: artemis
    password: simetraehcapa
  # port configuration to zipkin
  zipkin:
    enabled: false
  # spring security basic authentication configuration
  security:
    user:
      name: zeeroiq
      password: password

logging:
  level:
    com:
      shri: debug